version: '3'

services:
    magenode:
        image: "mage/mage:v0.12.0"
        ports:
            # open default mage rpc port
            - "26657:26657"
        volumes:
            - "./mage/initstate/.mgd/config:/root/.mgd/config"
            - "./mage/initstate/.kvcli/config:/root/.kvcli/config"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.mgd/config/init-data-directory.sh && mgd start --pruning=nothing --rpc.laddr=tcp://0.0.0.0:26657"]
    magerest:
        image: "mage/mage:v0.12.0"
        ports:
            # open default rest port
            - "1317:1317"
        command: ["kvcli", "rest-server", "--node=tcp://magenode:26657", "--trust-node", "--laddr=tcp://0.0.0.0:1317", "--unsafe-cors"]
