version: '3'
services:
    magenode:
        image: "mage/mage:master"
        ports:
            # open default mage rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
            # open EVM JSON-RPC port
            - "8545:8545"
            # open Eth websocket port
            - "8546:8546"
        volumes:
            - "./mage/initstate/.mage/config:/root/.mage/config"
            - "./mage/initstate/.mage/keyring-test/:/root/.mage/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command:
            - "sh"
            - "-c"
            - "/root/.mage/config/init-data-directory.sh && mage start --rpc.laddr=tcp://0.0.0.0:26657"
